### ISSUE TITLE
when will you release the dataset?

### ISSUE THREAD

**Issue by sibangde** [dokyeongK/DALE#1]
Thank you for your interesting work, and I want to know when will you release the dataset?

**Comment by dokyeongK** [comment]
Thank you for your attention! Sorry.. we preparing to extend [DALE] as a
journal. we will release the dataset if we finish this work. Thank you :-)

**Comment by Dongshengjiang** [comment]
waiting +1

**Comment by Qyizos** [comment]
waiting +1

**Comment by xhlho** [comment]
Hello, have the dataset and pre trained model been released yet?
